# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Food On Your Mind Shoping List' do


	pod 'BubbleTransition', '~> 0.1'

	use_frameworks!

end

target 'Food On Your Mind Shoping ListTests' do

end
use_frameworks!

